# Generated by Django 2.2 on 2020-11-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nod_problem', models.CharField(choices=[('Nod Problem 1', 'Nod Problem 1'), ('Nod Problem 2', 'Nod Problem 2'), ('Nod Problem 3', 'Nod Problem 3'), ('Nod Problem 4', 'Nod Problem 4'), ('Nod Problem 5', 'Nod Problem 5')], max_length=20)),
                ('mission_line', models.CharField(choices=[('Mission Line 1', 'Mission Line 1'), ('Mission Line 2', 'Mission Line 2'), ('Mission Line 3', 'Mission Line 3'), ('Mission Line 4', 'Mission Line 4'), ('Mission Line 5', 'Mission Line 5')], max_length=30)),
                ('secondary_mission_line', models.CharField(blank=True, choices=[('Mission Line 1', 'Mission Line 1'), ('Mission Line 2', 'Mission Line 2'), ('Mission Line 3', 'Mission Line 3'), ('Mission Line 4', 'Mission Line 4'), ('Mission Line 5', 'Mission Line 5')], max_length=30, null=True)),
                ('project_title', models.CharField(max_length=255)),
                ('analytic_intent', models.TextField(blank=True)),
                ('project_lead', models.CharField(choices=[('SMITH, JEFF', 'SMITH, JEFF'), ('MAY, ERIC', 'MAY, ERIC'), ('HOWARD, JOHN', 'HOWARD, JOHN')], max_length=100)),
                ('lead_office', models.CharField(choices=[('ACN', 'ACN'), ('ACNA', 'ACNA'), ('ACNI', 'ACNI'), ('ACNL', 'ACNL'), ('ACNQ', 'ACNQ'), ('ACNS', 'ACNS'), ('ACNW', 'ACNW')], max_length=50)),
                ('contributors', models.CharField(blank=True, max_length=255)),
                ('product_types', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('MED', 'MED'), ('LOW', 'LOW')], max_length=10)),
                ('project_status', models.CharField(blank=True, choices=[('WORKING', 'WORKING'), ('ON HOLD', 'ON HOLD'), ('CANCELLED', 'CANCELLED')], max_length=10)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('project_due_date', models.DateField(blank=True, null=True)),
                ('project_complete_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_creator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to='src.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='has_created_comments', to='src.User')),
                ('comment_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_comments', to='src.Project')),
            ],
        ),
    ]
